# permissions for end users to view pluginconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pluginconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apisix-operator
    app.kubernetes.io/part-of: apisix-operator
    app.kubernetes.io/managed-by: kustomize
  name: pluginconfig-viewer-role
rules:
- apiGroups:
  - gateway.apisix.apache.org
  resources:
  - pluginconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.apisix.apache.org
  resources:
  - pluginconfigs/status
  verbs:
  - get
