---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gateway.apisix.apache.org
  resources:
  - pluginconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.apisix.apache.org
  resources:
  - pluginconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.apisix.apache.org
  resources:
  - pluginconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - HTTPRoutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - HTTPRoutes/status
  verbs:
  - get
  - update
