// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: proto/adminapi/route.proto

package adminapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// https://apisix.apache.org/docs/apisix/admin-api/#route-api
type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc     string            `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Labels   map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Uris     []string          `protobuf:"bytes,4,rep,name=uris,proto3" json:"uris,omitempty"`
	Hosts    []string          `protobuf:"bytes,5,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Upstream *Upstream         `protobuf:"bytes,6,opt,name=upstream,proto3" json:"upstream,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_adminapi_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adminapi_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_proto_adminapi_route_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Route) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Route) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *Route) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Route) GetUpstream() *Upstream {
	if x != nil {
		return x.Upstream
	}
	return nil
}

var File_proto_adminapi_route_proto protoreflect.FileDescriptor

var file_proto_adminapi_route_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x70,
	0x69, 0x73, 0x69, 0x78, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x1a, 0x1d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x70,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x02, 0x0a,
	0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x3a,
	0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72,
	0x69, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x69, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68,
	0x6f, 0x73, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x69, 0x78, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x08, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x39, 0x0a, 0x0b, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_adminapi_route_proto_rawDescOnce sync.Once
	file_proto_adminapi_route_proto_rawDescData = file_proto_adminapi_route_proto_rawDesc
)

func file_proto_adminapi_route_proto_rawDescGZIP() []byte {
	file_proto_adminapi_route_proto_rawDescOnce.Do(func() {
		file_proto_adminapi_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_adminapi_route_proto_rawDescData)
	})
	return file_proto_adminapi_route_proto_rawDescData
}

var file_proto_adminapi_route_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_adminapi_route_proto_goTypes = []interface{}{
	(*Route)(nil),    // 0: apisix.adminapi.Route
	nil,              // 1: apisix.adminapi.Route.LabelsEntry
	(*Upstream)(nil), // 2: apisix.adminapi.Upstream
}
var file_proto_adminapi_route_proto_depIdxs = []int32{
	1, // 0: apisix.adminapi.Route.labels:type_name -> apisix.adminapi.Route.LabelsEntry
	2, // 1: apisix.adminapi.Route.upstream:type_name -> apisix.adminapi.Upstream
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_adminapi_route_proto_init() }
func file_proto_adminapi_route_proto_init() {
	if File_proto_adminapi_route_proto != nil {
		return
	}
	file_proto_adminapi_upstream_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_adminapi_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_adminapi_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_adminapi_route_proto_goTypes,
		DependencyIndexes: file_proto_adminapi_route_proto_depIdxs,
		MessageInfos:      file_proto_adminapi_route_proto_msgTypes,
	}.Build()
	File_proto_adminapi_route_proto = out.File
	file_proto_adminapi_route_proto_rawDesc = nil
	file_proto_adminapi_route_proto_goTypes = nil
	file_proto_adminapi_route_proto_depIdxs = nil
}
